image: docker:latest

stages:
  - build

docker-build:
  stage: build
  image: docker:latest
  script:
    - docker login -u $ALIYUN_REGISTRY_USERNAME -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY
    - docker build -t $ALIYUN_REGISTRY/$ALIYUN_REGISTRY_NAMESPACE/$CI_PROJECT_NAME:latest .
    - docker push $ALIYUN_REGISTRY/$ALIYUN_REGISTRY_NAMESPACE/$CI_PROJECT_NAME:latest
  only:
    - main
