image: docker:latest

variables:
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  USERNAME: admin@yuanfen.net
  PASSWORD: 4J0RPue8Zgifql9J
  NAMESPACE: yuanfen
  PROJECT_NAME: yf-tools-web

stages:
  - build

docker-build:
  stage: build
  image: docker:latest
  script:
    - docker login --username=$USERNAME $REGISTRY -p $PASSWORD
    - docker build -t $REGISTRY/$NAMESPACE/$PROJECT_NAME:$CI_COMMIT_REF_NAME -t $REGISTRY/$NAMESPACE/$PROJECT_NAME:latest .
    - docker push $REGISTRY/$NAMESPACE/$PROJECT_NAME:$CI_COMMIT_REF_NAME
    - docker push $REGISTRY/$NAMESPACE/$PROJECT_NAME:latest
    - docker rmi $REGISTRY/$NAMESPACE/$PROJECT_NAME:$CI_COMMIT_REF_NAME
  only:
    - tags
